import builder_modules.htcl_template as htcl


node = htcl.HtclNode()
print(node.is_component())


# import time
# import builder_modules.loading_bar as load_bar



# loading_bar = load_bar.LoadingBar(26, "Init")
# loading_bar.load("a these")
# time.sleep(0.5)
# loading_bar.load("b are")
# time.sleep(0.5)
# loading_bar.load("c messages of")
# time.sleep(0.5)
# loading_bar.load("d various")
# time.sleep(0.5)
# loading_bar.load("e lengths")
# time.sleep(0.5)
# loading_bar.load("f to test the overriding and message")
# time.sleep(0.5)
# loading_bar.load("g capability")
# time.sleep(0.5)
# loading_bar.load("h meow")
# time.sleep(0.5)
# loading_bar.load("i")
# time.sleep(0.5)
# loading_bar.load("j")
# time.sleep(0.5)
# loading_bar.load("k")
# time.sleep(0.5)
# loading_bar.load("l")
# time.sleep(0.5)
# loading_bar.load("m")
# time.sleep(0.5)
# loading_bar.load("n")
# time.sleep(0.5)
# loading_bar.load("o")
# time.sleep(0.5)
# loading_bar.load("p")
# time.sleep(0.5)
# loading_bar.load("q")
# time.sleep(0.5)
# loading_bar.load("r")
# time.sleep(0.5)
# loading_bar.load("s")
# time.sleep(0.5)
# loading_bar.load("t")
# time.sleep(0.5)
# loading_bar.load("u")
# time.sleep(0.5)
# loading_bar.load("v")
# time.sleep(0.5)
# loading_bar.load("w")
# time.sleep(0.5)
# loading_bar.load("x")
# time.sleep(0.5)
# loading_bar.load("y")
# time.sleep(0.5)
# loading_bar.load("z")
# time.sleep(0.5)
